version: '3.8'
services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
  nginx:
    image: nginx:1.19-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
  backend:
    image: hello-backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    image: hello-frontend
    ports:
      - "5000:5000"
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  db:
  nginx:
