version: "3.8"

services:
  express-app:
    image: sachinbro/coursepage:latest
    ports:
      - 3000:8080

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 5
