version: '3.8'
services:
  backend:
    image: hello-backend
    environment:
      - REDIS_HOST=redis
    ports:
      - "8080:8080"
  frontend:
    image: hello-frontend
    ports:
      - "5000:5000"
  redis:
    image: redis
    ports:
      - "6379:6379"
